namespace Swav2Swar
{
	// Token: 0x02000008 RID: 8
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Principal : global::System.Windows.Forms.Form
	{
		// Token: 0x06000020 RID: 32 RVA: 0x00004D40 File Offset: 0x00003140
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000021 RID: 33 RVA: 0x00004D80 File Offset: 0x00003180
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Swav2Swar.Principal));
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.Tab = new global::System.Windows.Forms.TabControl();
			this.Tab1 = new global::System.Windows.Forms.TabPage();
			this.Abrir = new global::System.Windows.Forms.Button();
			this.Ayuda = new global::System.Windows.Forms.Button();
			this.CrearSwar = new global::System.Windows.Forms.Button();
			this.Subir = new global::System.Windows.Forms.Button();
			this.Bajar = new global::System.Windows.Forms.Button();
			this.Grid1 = new global::System.Windows.Forms.DataGridView();
			this.Ruta = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.indice = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Nombre = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Tab2 = new global::System.Windows.Forms.TabPage();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.PCM8 = new global::System.Windows.Forms.RadioButton();
			this.IMA = new global::System.Windows.Forms.RadioButton();
			this.PCM16 = new global::System.Windows.Forms.RadioButton();
			this.AbrirWav = new global::System.Windows.Forms.Button();
			this.CrearSwav = new global::System.Windows.Forms.Button();
			this.NombreFichero = new global::System.Windows.Forms.TextBox();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Canales = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Frecuencia = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.TipoOnda = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.ObjetoOpenFile = new global::System.Windows.Forms.OpenFileDialog();
			this.ObjetoSaveFile = new global::System.Windows.Forms.SaveFileDialog();
			this.Tab.SuspendLayout();
			this.Tab1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Grid1).BeginInit();
			this.Tab2.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.SuspendLayout();
			this.Tab.Controls.Add(this.Tab1);
			this.Tab.Controls.Add(this.Tab2);
			global::System.Windows.Forms.Control tab = this.Tab;
			global::System.Drawing.Point location = new global::System.Drawing.Point(12, 12);
			tab.Location = location;
			this.Tab.Name = "Tab";
			this.Tab.SelectedIndex = 0;
			global::System.Windows.Forms.Control tab2 = this.Tab;
			global::System.Drawing.Size size = new global::System.Drawing.Size(311, 270);
			tab2.Size = size;
			this.Tab.TabIndex = 18;
			this.Tab1.Controls.Add(this.Abrir);
			this.Tab1.Controls.Add(this.Ayuda);
			this.Tab1.Controls.Add(this.CrearSwar);
			this.Tab1.Controls.Add(this.Subir);
			this.Tab1.Controls.Add(this.Bajar);
			this.Tab1.Controls.Add(this.Grid1);
			global::System.Windows.Forms.TabPage tab3 = this.Tab1;
			location = new global::System.Drawing.Point(4, 22);
			tab3.Location = location;
			this.Tab1.Name = "Tab1";
			global::System.Windows.Forms.Control tab4 = this.Tab1;
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(3);
			tab4.Padding = padding;
			global::System.Windows.Forms.Control tab5 = this.Tab1;
			size = new global::System.Drawing.Size(303, 244);
			tab5.Size = size;
			this.Tab1.TabIndex = 0;
			this.Tab1.Text = "SWAV -> SWAR";
			this.Tab1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control abrir = this.Abrir;
			location = new global::System.Drawing.Point(6, 215);
			abrir.Location = location;
			this.Abrir.Name = "Abrir";
			global::System.Windows.Forms.Control abrir2 = this.Abrir;
			size = new global::System.Drawing.Size(34, 22);
			abrir2.Size = size;
			this.Abrir.TabIndex = 72;
			this.Abrir.Text = "&Add";
			this.Abrir.UseVisualStyleBackColor = true;
			this.Ayuda.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Ayuda.Image");
			global::System.Windows.Forms.Control ayuda = this.Ayuda;
			location = new global::System.Drawing.Point(273, 6);
			ayuda.Location = location;
			this.Ayuda.Name = "Ayuda";
			global::System.Windows.Forms.Control ayuda2 = this.Ayuda;
			size = new global::System.Drawing.Size(24, 24);
			ayuda2.Size = size;
			this.Ayuda.TabIndex = 71;
			this.Ayuda.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control crearSwar = this.CrearSwar;
			location = new global::System.Drawing.Point(87, 215);
			crearSwar.Location = location;
			this.CrearSwar.Name = "CrearSwar";
			global::System.Windows.Forms.Control crearSwar2 = this.CrearSwar;
			size = new global::System.Drawing.Size(128, 23);
			crearSwar2.Size = size;
			this.CrearSwar.TabIndex = 70;
			this.CrearSwar.Text = "&Create SWAR";
			this.CrearSwar.UseVisualStyleBackColor = true;
			this.Subir.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Subir.Image");
			global::System.Windows.Forms.Control subir = this.Subir;
			location = new global::System.Drawing.Point(273, 155);
			subir.Location = location;
			this.Subir.Name = "Subir";
			global::System.Windows.Forms.Control subir2 = this.Subir;
			size = new global::System.Drawing.Size(24, 24);
			subir2.Size = size;
			this.Subir.TabIndex = 68;
			this.Subir.TabStop = false;
			this.Subir.UseVisualStyleBackColor = true;
			this.Bajar.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Bajar.Image");
			global::System.Windows.Forms.Control bajar = this.Bajar;
			location = new global::System.Drawing.Point(273, 185);
			bajar.Location = location;
			this.Bajar.Name = "Bajar";
			global::System.Windows.Forms.Control bajar2 = this.Bajar;
			size = new global::System.Drawing.Size(24, 24);
			bajar2.Size = size;
			this.Bajar.TabIndex = 69;
			this.Bajar.TabStop = false;
			this.Bajar.UseVisualStyleBackColor = true;
			this.Grid1.AllowDrop = true;
			this.Grid1.AllowUserToAddRows = false;
			this.Grid1.AllowUserToResizeColumns = false;
			this.Grid1.AllowUserToResizeRows = false;
			dataGridViewCellStyle.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
			dataGridViewCellStyle.BackColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle.ForeColor = global::System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.Grid1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.Grid1.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.Grid1.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Ruta,
				this.indice,
				this.Nombre
			});
			global::System.Windows.Forms.Control grid = this.Grid1;
			location = new global::System.Drawing.Point(6, 6);
			grid.Location = location;
			this.Grid1.MultiSelect = false;
			this.Grid1.Name = "Grid1";
			this.Grid1.ReadOnly = true;
			this.Grid1.RowHeadersVisible = false;
			this.Grid1.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			global::System.Windows.Forms.Control grid2 = this.Grid1;
			size = new global::System.Drawing.Size(261, 203);
			grid2.Size = size;
			this.Grid1.TabIndex = 0;
			this.Ruta.HeaderText = "Ruta";
			this.Ruta.Name = "Ruta";
			this.Ruta.ReadOnly = true;
			this.Ruta.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Ruta.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Ruta.Visible = false;
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
			this.indice.DefaultCellStyle = dataGridViewCellStyle2;
			this.indice.HeaderText = "Index";
			this.indice.Name = "indice";
			this.indice.ReadOnly = true;
			this.indice.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.indice.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.indice.Width = 45;
			this.Nombre.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.Nombre.HeaderText = "Name";
			this.Nombre.Name = "Nombre";
			this.Nombre.ReadOnly = true;
			this.Nombre.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Nombre.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Tab2.Controls.Add(this.GroupBox2);
			this.Tab2.Controls.Add(this.AbrirWav);
			this.Tab2.Controls.Add(this.CrearSwav);
			this.Tab2.Controls.Add(this.NombreFichero);
			this.Tab2.Controls.Add(this.GroupBox1);
			global::System.Windows.Forms.TabPage tab6 = this.Tab2;
			location = new global::System.Drawing.Point(4, 22);
			tab6.Location = location;
			this.Tab2.Name = "Tab2";
			global::System.Windows.Forms.Control tab7 = this.Tab2;
			padding = new global::System.Windows.Forms.Padding(3);
			tab7.Padding = padding;
			global::System.Windows.Forms.Control tab8 = this.Tab2;
			size = new global::System.Drawing.Size(303, 244);
			tab8.Size = size;
			this.Tab2.TabIndex = 1;
			this.Tab2.Text = "WAV -> SWAV";
			this.Tab2.UseVisualStyleBackColor = true;
			this.GroupBox2.Controls.Add(this.PCM8);
			this.GroupBox2.Controls.Add(this.IMA);
			this.GroupBox2.Controls.Add(this.PCM16);
			global::System.Windows.Forms.Control groupBox = this.GroupBox2;
			location = new global::System.Drawing.Point(35, 156);
			groupBox.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox2;
			size = new global::System.Drawing.Size(227, 29);
			groupBox2.Size = size;
			this.GroupBox2.TabIndex = 14;
			this.GroupBox2.TabStop = false;
			this.PCM8.AutoSize = true;
			global::System.Windows.Forms.Control pcm = this.PCM8;
			location = new global::System.Drawing.Point(101, 8);
			pcm.Location = location;
			this.PCM8.Name = "PCM8";
			global::System.Windows.Forms.Control pcm2 = this.PCM8;
			size = new global::System.Drawing.Size(54, 17);
			pcm2.Size = size;
			this.PCM8.TabIndex = 9;
			this.PCM8.Text = "PCM8";
			this.PCM8.UseVisualStyleBackColor = true;
			this.IMA.AutoSize = true;
			this.IMA.Checked = true;
			global::System.Windows.Forms.Control ima = this.IMA;
			location = new global::System.Drawing.Point(10, 8);
			ima.Location = location;
			this.IMA.Name = "IMA";
			global::System.Windows.Forms.Control ima2 = this.IMA;
			size = new global::System.Drawing.Size(85, 17);
			ima2.Size = size;
			this.IMA.TabIndex = 11;
			this.IMA.TabStop = true;
			this.IMA.Text = "IMA-ADPCM";
			this.IMA.UseVisualStyleBackColor = true;
			this.PCM16.AutoSize = true;
			global::System.Windows.Forms.Control pcm3 = this.PCM16;
			location = new global::System.Drawing.Point(161, 8);
			pcm3.Location = location;
			this.PCM16.Name = "PCM16";
			global::System.Windows.Forms.Control pcm4 = this.PCM16;
			size = new global::System.Drawing.Size(60, 17);
			pcm4.Size = size;
			this.PCM16.TabIndex = 10;
			this.PCM16.Text = "PCM16";
			this.PCM16.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control abrirWav = this.AbrirWav;
			location = new global::System.Drawing.Point(226, 10);
			abrirWav.Location = location;
			this.AbrirWav.Name = "AbrirWav";
			global::System.Windows.Forms.Control abrirWav2 = this.AbrirWav;
			size = new global::System.Drawing.Size(71, 24);
			abrirWav2.Size = size;
			this.AbrirWav.TabIndex = 9;
			this.AbrirWav.Text = "&Open WAV";
			this.AbrirWav.UseVisualStyleBackColor = true;
			this.CrearSwav.Enabled = false;
			global::System.Windows.Forms.Control crearSwav = this.CrearSwav;
			location = new global::System.Drawing.Point(106, 197);
			crearSwav.Location = location;
			this.CrearSwav.Name = "CrearSwav";
			global::System.Windows.Forms.Control crearSwav2 = this.CrearSwav;
			size = new global::System.Drawing.Size(79, 24);
			crearSwav2.Size = size;
			this.CrearSwav.TabIndex = 8;
			this.CrearSwav.Text = "&Save";
			this.CrearSwav.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control nombreFichero = this.NombreFichero;
			location = new global::System.Drawing.Point(6, 12);
			nombreFichero.Location = location;
			this.NombreFichero.Name = "NombreFichero";
			this.NombreFichero.ReadOnly = true;
			global::System.Windows.Forms.Control nombreFichero2 = this.NombreFichero;
			size = new global::System.Drawing.Size(214, 20);
			nombreFichero2.Size = size;
			this.NombreFichero.TabIndex = 8;
			this.GroupBox1.Controls.Add(this.Canales);
			this.GroupBox1.Controls.Add(this.Label2);
			this.GroupBox1.Controls.Add(this.Frecuencia);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.TipoOnda);
			this.GroupBox1.Controls.Add(this.Label3);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox1;
			location = new global::System.Drawing.Point(6, 48);
			groupBox3.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox1;
			size = new global::System.Drawing.Size(291, 92);
			groupBox4.Size = size;
			this.GroupBox1.TabIndex = 7;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "WAV Info";
			this.Canales.AutoSize = true;
			global::System.Windows.Forms.Control canales = this.Canales;
			location = new global::System.Drawing.Point(72, 66);
			canales.Location = location;
			this.Canales.Name = "Canales";
			global::System.Windows.Forms.Control canales2 = this.Canales;
			size = new global::System.Drawing.Size(16, 13);
			canales2.Size = size;
			this.Canales.TabIndex = 5;
			this.Canales.Text = "...";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label2;
			location = new global::System.Drawing.Point(15, 44);
			label.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label2 = this.Label2;
			size = new global::System.Drawing.Size(74, 13);
			label2.Size = size;
			this.Label2.TabIndex = 1;
			this.Label2.Text = "Sample Rate :";
			this.Frecuencia.AutoSize = true;
			global::System.Windows.Forms.Control frecuencia = this.Frecuencia;
			location = new global::System.Drawing.Point(95, 44);
			frecuencia.Location = location;
			this.Frecuencia.Name = "Frecuencia";
			global::System.Windows.Forms.Control frecuencia2 = this.Frecuencia;
			size = new global::System.Drawing.Size(16, 13);
			frecuencia2.Size = size;
			this.Frecuencia.TabIndex = 4;
			this.Frecuencia.Text = "...";
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label1;
			location = new global::System.Drawing.Point(15, 22);
			label3.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label4 = this.Label1;
			size = new global::System.Drawing.Size(78, 13);
			label4.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "Audio Format  :";
			this.TipoOnda.AutoSize = true;
			global::System.Windows.Forms.Control tipoOnda = this.TipoOnda;
			location = new global::System.Drawing.Point(94, 22);
			tipoOnda.Location = location;
			this.TipoOnda.Name = "TipoOnda";
			global::System.Windows.Forms.Control tipoOnda2 = this.TipoOnda;
			size = new global::System.Drawing.Size(16, 13);
			tipoOnda2.Size = size;
			this.TipoOnda.TabIndex = 3;
			this.TipoOnda.Text = "...";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label3;
			location = new global::System.Drawing.Point(15, 66);
			label5.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new global::System.Drawing.Size(57, 13);
			label6.Size = size;
			this.Label3.TabIndex = 2;
			this.Label3.Text = "Channels :";
			this.ObjetoOpenFile.FileName = "OpenFileDialog1";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(334, 295);
			this.ClientSize = size;
			this.Controls.Add(this.Tab);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.MaximizeBox = false;
			this.Name = "Principal";
			this.Text = "Swav2Swar Converter v0.1";
			this.Tab.ResumeLayout(false);
			this.Tab1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.Grid1).EndInit();
			this.Tab2.ResumeLayout(false);
			this.Tab2.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x0400000A RID: 10
		private global::System.ComponentModel.IContainer components;
	}
}
